-- Patch (CÁCH CŨ - ghi đè title gốc): Cập nhật title eb_system_config_tab sang tiếng Việt
-- Khuyến nghị: Dùng patch đa ngôn ngữ INSERT thay vì UPDATE: patch_system_config_tab_lang_vi.sql
--   (tạo bảng eb_system_config_tab_lang + INSERT bản dịch, không sửa bảng gốc; backend trả title theo header cb-lang)
-- Chạy sau khi cài đặt CRMEB (MySQL). Nguồn: eb_system_config_tab từ crmeb.sql

UPDATE eb_system_config_tab SET title = 'Cấu hình cơ bản' WHERE id = 1;
UPDATE eb_system_config_tab SET title = 'Cấu hình công khai (H5)' WHERE id = 2;
UPDATE eb_system_config_tab SET title = 'Cấu hình thanh toán WeChat' WHERE id = 4;
UPDATE eb_system_config_tab SET title = 'Cấu hình mini app' WHERE id = 7;
UPDATE eb_system_config_tab SET title = 'Cấu hình phân phối' WHERE id = 9;
UPDATE eb_system_config_tab SET title = 'Cấu hình điểm người dùng' WHERE id = 11;
UPDATE eb_system_config_tab SET title = 'Nhất thông (SMS)' WHERE id = 18;
UPDATE eb_system_config_tab SET title = 'Cấu hình thanh toán cửa hàng' WHERE id = 23;
UPDATE eb_system_config_tab SET title = 'Cấu hình nạp tiền' WHERE id = 28;
UPDATE eb_system_config_tab SET title = 'Cấu hình cơ bản' WHERE id = 31;
UPDATE eb_system_config_tab SET title = 'Cấu hình thu thập sản phẩm' WHERE id = 41;
UPDATE eb_system_config_tab SET title = 'Cấu hình cấp độ người dùng' WHERE id = 45;
UPDATE eb_system_config_tab SET title = 'Cấu hình hóa đơn' WHERE id = 50;
UPDATE eb_system_config_tab SET title = 'Cấu hình thanh toán Alipay' WHERE id = 63;
UPDATE eb_system_config_tab SET title = 'Cấu hình tra cứu logistics' WHERE id = 64;
UPDATE eb_system_config_tab SET title = 'Cài đặt giao diện' WHERE id = 65;
UPDATE eb_system_config_tab SET title = 'Cấu hình phiếu điện tử' WHERE id = 66;
UPDATE eb_system_config_tab SET title = 'Cấu hình hội viên trả phí' WHERE id = 67;
UPDATE eb_system_config_tab SET title = 'Cấu hình dịch vụ khách hàng' WHERE id = 69;
UPDATE eb_system_config_tab SET title = 'Cấu hình chia sẻ' WHERE id = 70;
UPDATE eb_system_config_tab SET title = 'Cấu hình hoàn tiền / đổi trả' WHERE id = 71;
UPDATE eb_system_config_tab SET title = 'Chế độ phân phối' WHERE id = 72;
UPDATE eb_system_config_tab SET title = 'Cài đặt hoa hồng' WHERE id = 73;
UPDATE eb_system_config_tab SET title = 'Cài đặt rút tiền' WHERE id = 74;
UPDATE eb_system_config_tab SET title = 'Cấu hình site PC' WHERE id = 75;
UPDATE eb_system_config_tab SET title = 'Cấu hình APP' WHERE id = 77;
UPDATE eb_system_config_tab SET title = 'Cấu hình ứng dụng' WHERE id = 78;
UPDATE eb_system_config_tab SET title = 'Cấu hình lưu trữ hệ thống' WHERE id = 79;
UPDATE eb_system_config_tab SET title = 'Cấu hình Qiniu' WHERE id = 80;
UPDATE eb_system_config_tab SET title = 'Cấu hình Aliyun' WHERE id = 81;
UPDATE eb_system_config_tab SET title = 'Cấu hình Tencent Cloud' WHERE id = 82;
UPDATE eb_system_config_tab SET title = 'Cấu hình cơ bản (thu thập)' WHERE id = 89;
UPDATE eb_system_config_tab SET title = 'Cấu hình 99api' WHERE id = 90;
UPDATE eb_system_config_tab SET title = 'Cấu hình cơ bản (logistics)' WHERE id = 91;
UPDATE eb_system_config_tab SET title = 'Cấu hình Aliyun (logistics)' WHERE id = 92;
UPDATE eb_system_config_tab SET title = 'Cấu hình cơ bản (phiếu)' WHERE id = 93;
UPDATE eb_system_config_tab SET title = 'Cấu hình Nhất thông (phiếu)' WHERE id = 94;
UPDATE eb_system_config_tab SET title = 'Cấu hình SMS' WHERE id = 96;
UPDATE eb_system_config_tab SET title = 'Cấu hình cơ bản (SMS)' WHERE id = 97;
UPDATE eb_system_config_tab SET title = 'Cấu hình Aliyun (SMS)' WHERE id = 98;
UPDATE eb_system_config_tab SET title = 'Cấu hình Tencent (SMS)' WHERE id = 99;
UPDATE eb_system_config_tab SET title = 'Cấu hình người dùng' WHERE id = 100;
UPDATE eb_system_config_tab SET title = 'Cấu hình giao diện đối ngoại' WHERE id = 102;
UPDATE eb_system_config_tab SET title = 'Cấu hình cơ bản (đối ngoại)' WHERE id = 103;
UPDATE eb_system_config_tab SET title = 'Cấu hình đẩy (đối ngoại)' WHERE id = 104;
UPDATE eb_system_config_tab SET title = 'Cài đặt người dùng mới' WHERE id = 105;
UPDATE eb_system_config_tab SET title = 'Cấu hình dịch trực tuyến' WHERE id = 106;
UPDATE eb_system_config_tab SET title = 'Thanh toán Thông Liên' WHERE id = 108;
UPDATE eb_system_config_tab SET title = 'Cấu hình cơ bản (thanh toán)' WHERE id = 109;
UPDATE eb_system_config_tab SET title = 'Cấu hình JD Cloud' WHERE id = 110;
UPDATE eb_system_config_tab SET title = 'Cấu hình Huawei Cloud' WHERE id = 111;
UPDATE eb_system_config_tab SET title = 'Cấu hình Tianyi Cloud' WHERE id = 112;
UPDATE eb_system_config_tab SET title = 'Cấu hình đơn hàng' WHERE id = 113;
UPDATE eb_system_config_tab SET title = 'Cài đặt miễn phí vận chuyển' WHERE id = 114;
UPDATE eb_system_config_tab SET title = 'Cấu hình hủy đơn' WHERE id = 115;
UPDATE eb_system_config_tab SET title = 'Cấu hình tự nhận hàng' WHERE id = 116;
UPDATE eb_system_config_tab SET title = 'Cấu hình tự đánh giá' WHERE id = 117;
UPDATE eb_system_config_tab SET title = 'Cấu hình tự nhận tại cửa hàng' WHERE id = 119;
UPDATE eb_system_config_tab SET title = 'Cấu hình tồn kho cảnh báo' WHERE id = 120;
UPDATE eb_system_config_tab SET title = 'Cấu hình LOGO' WHERE id = 122;
UPDATE eb_system_config_tab SET title = 'JS tùy chỉnh' WHERE id = 123;
UPDATE eb_system_config_tab SET title = 'Cấu hình bản đồ' WHERE id = 124;
UPDATE eb_system_config_tab SET title = 'Cấu hình ICP/beian' WHERE id = 125;
UPDATE eb_system_config_tab SET title = 'Cấu hình điểm danh' WHERE id = 126;
UPDATE eb_system_config_tab SET title = 'Cấu hình hệ thống' WHERE id = 129;
UPDATE eb_system_config_tab SET title = 'Cấu hình công khai' WHERE id = 130;
UPDATE eb_system_config_tab SET title = 'Cấu hình tên miền máy chủ' WHERE id = 131;
UPDATE eb_system_config_tab SET title = 'Cấu hình mini app' WHERE id = 132;
UPDATE eb_system_config_tab SET title = 'Cấu hình đẩy tin' WHERE id = 133;
UPDATE eb_system_config_tab SET title = 'Cấu hình module' WHERE id = 134;
UPDATE eb_system_config_tab SET title = 'Cấu hình đăng nhập từ xa' WHERE id = 135;
UPDATE eb_system_config_tab SET title = 'Cấu hình sản phẩm' WHERE id = 136;
UPDATE eb_system_config_tab SET title = 'Cấu hình WAF' WHERE id = 137;
