-- Patch: Đa ngôn ngữ tab Cài đặt hệ thống (INSERT bản dịch tiếng Việt)
-- Sinh bởi scripts/patch_system_config_vi.py từ crmeb.sql
-- lang_type_id = 10 (vi-VN). Chạy sau khi đã import crmeb.sql.

CREATE TABLE IF NOT EXISTS `eb_system_config_tab_lang` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `tab_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'ID tab (eb_system_config_tab.id)',
  `lang_type_id` int(11) NOT NULL DEFAULT '0' COMMENT 'Ngôn ngữ (10=vi-VN)',
  `title` varchar(255) NOT NULL DEFAULT '' COMMENT 'Tên tab theo ngôn ngữ',
  PRIMARY KEY (`id`),
  UNIQUE KEY `tab_lang` (`tab_id`,`lang_type_id`),
  KEY `lang_type_id` (`lang_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Bản dịch tên tab cấu hình';

INSERT INTO `eb_system_config_tab_lang` (`tab_id`, `lang_type_id`, `title`) VALUES
(1, 10, 'Cấu hình cơ bản'),
(2, 10, 'Cấu hình công khai (H5)'),
(4, 10, 'Cấu hình thanh toán WeChat'),
(7, 10, 'Cấu hình mini app'),
(9, 10, 'Cấu hình phân phối'),
(11, 10, 'Cấu hình điểm người dùng'),
(18, 10, 'Nhất thông (SMS)'),
(23, 10, 'Cấu hình thanh toán cửa hàng'),
(28, 10, 'Cấu hình nạp tiền'),
(31, 10, 'Cấu hình cơ bản'),
(41, 10, 'Cấu hình thu thập sản phẩm'),
(45, 10, 'Cấu hình cấp độ người dùng'),
(50, 10, 'Cấu hình hóa đơn'),
(63, 10, 'Cấu hình thanh toán Alipay'),
(64, 10, 'Cấu hình tra cứu logistics'),
(65, 10, 'Cài đặt giao diện'),
(66, 10, 'Cấu hình phiếu điện tử'),
(67, 10, 'Cấu hình hội viên trả phí'),
(69, 10, 'Cấu hình dịch vụ khách hàng'),
(70, 10, 'Cấu hình chia sẻ'),
(71, 10, 'Cấu hình hoàn tiền / đổi trả'),
(72, 10, 'Chế độ phân phối'),
(73, 10, 'Cài đặt hoa hồng'),
(74, 10, 'Cài đặt rút tiền'),
(75, 10, 'Cấu hình site PC'),
(77, 10, 'Cấu hình APP'),
(78, 10, 'Cấu hình ứng dụng'),
(79, 10, 'Cấu hình lưu trữ hệ thống'),
(80, 10, 'Cấu hình Qiniu'),
(81, 10, 'Cấu hình Aliyun'),
(82, 10, 'Cấu hình Tencent Cloud'),
(89, 10, 'Cấu hình cơ bản (thu thập)'),
(90, 10, 'Cấu hình 99api'),
(91, 10, 'Cấu hình cơ bản (logistics)'),
(92, 10, 'Cấu hình Aliyun (logistics)'),
(93, 10, 'Cấu hình cơ bản (phiếu)'),
(94, 10, 'Cấu hình Nhất thông (phiếu)'),
(96, 10, 'Cấu hình SMS'),
(97, 10, 'Cấu hình cơ bản (SMS)'),
(98, 10, 'Cấu hình Aliyun (SMS)'),
(99, 10, 'Cấu hình Tencent (SMS)'),
(100, 10, 'Cấu hình người dùng'),
(102, 10, 'Cấu hình giao diện đối ngoại'),
(103, 10, 'Cấu hình cơ bản (đối ngoại)'),
(104, 10, 'Cấu hình đẩy (đối ngoại)'),
(105, 10, 'Cài đặt người dùng mới'),
(106, 10, 'Cấu hình dịch trực tuyến'),
(108, 10, 'Thanh toán Thông Liên'),
(109, 10, 'Cấu hình cơ bản (thanh toán)'),
(110, 10, 'Cấu hình JD Cloud'),
(111, 10, 'Cấu hình Huawei Cloud'),
(112, 10, 'Cấu hình Tianyi Cloud'),
(113, 10, 'Cấu hình đơn hàng'),
(114, 10, 'Cài đặt miễn phí vận chuyển'),
(115, 10, 'Cấu hình hủy đơn'),
(116, 10, 'Cấu hình tự nhận hàng'),
(117, 10, 'Cấu hình tự đánh giá'),
(119, 10, 'Cấu hình tự nhận tại cửa hàng'),
(120, 10, 'Cấu hình tồn kho cảnh báo'),
(122, 10, 'Cấu hình LOGO'),
(123, 10, 'JS tùy chỉnh'),
(124, 10, 'Cấu hình bản đồ'),
(125, 10, 'Cấu hình ICP/beian'),
(126, 10, 'Cấu hình điểm danh'),
(129, 10, 'Cấu hình hệ thống'),
(130, 10, 'Cấu hình công khai'),
(131, 10, 'Cấu hình tên miền máy chủ'),
(132, 10, 'Cấu hình mini app'),
(133, 10, 'Cấu hình đẩy tin'),
(134, 10, 'Cấu hình module'),
(135, 10, 'Cấu hình đăng nhập từ xa'),
(136, 10, 'Cấu hình sản phẩm'),
(137, 10, 'Cấu hình WAF')
ON DUPLICATE KEY UPDATE `title` = VALUES(`title`);
