-- Patch: Đa ngôn ngữ cho form cấu hình (INSERT vào eb_system_config_lang, không UPDATE bảng gốc)
-- Sinh bởi scripts/patch_system_config_vi.py từ crmeb.sql
-- lang_type_id = 10 (vi-VN). Backend đọc info/desc/parameter theo cb-lang.

CREATE TABLE IF NOT EXISTS `eb_system_config_lang` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `config_id` int(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'eb_system_config.id',
  `lang_type_id` int(11) NOT NULL DEFAULT '0' COMMENT 'eb_lang_type.id (10=vi-VN)',
  `info` varchar(255) NOT NULL DEFAULT '' COMMENT 'Tên hiển thị theo ngôn ngữ',
  `desc` varchar(255) NOT NULL DEFAULT '' COMMENT 'Mô tả theo ngôn ngữ',
  `parameter` varchar(255) NOT NULL DEFAULT '' COMMENT 'Tham số option theo ngôn ngữ',
  PRIMARY KEY (`id`),
  UNIQUE KEY `config_lang` (`config_id`,`lang_type_id`),
  KEY `lang_type_id` (`lang_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Bản dịch cấu hình (info, desc, parameter)';

INSERT INTO `eb_system_config_lang` (`config_id`, `lang_type_id`, `info`, `desc`, `parameter`) VALUES
(1, 10, 'Tên website', 'Dùng cho quản trị, PC, H5, chia sẻ trang, poster và các vị trí hiển thị tên website', ''),
(2, 10, 'Địa chỉ website', 'Khi cài đặt hệ thống sẽ tự cấu hình; không nên sửa tùy tiện. Thay đổi ảnh hưởng truy cập website, API, lưu trữ file, callback thanh toán, ủy quyền WeChat, thanh toán, ảnh mini app, mã QR, ủy quyền chính thức.', ''),
(3, 10, 'LOGO lớn quản trị', 'Logo góc trái trên khi mở menu, kích thước khuyến nghị [170x50]', ''),
(4, 10, 'Số điện thoại liên hệ', 'Số điện thoại liên hệ', ''),
(13, 10, 'AppID', 'AppID tài khoản WeChat công khai', ''),
(14, 10, 'AppSecret', 'AppSecret tài khoản WeChat công khai', ''),
(15, 10, 'TOKEN xác thực WeChat', 'TOKEN xác thực WeChat', ''),
(16, 10, 'Cách thức mã hóa/giải mã tin nhắn', 'Dùng chế độ bảo mật cần sửa trong trung tâm quản lý WeChat; chỉ áp dụng tài khoản dịch vụ và đăng ký đã xác thực', '0=>Chế độ văn bản rõ\n1=>Chế độ tương thích\n2=>Chế độ bảo mật'),
(17, 10, 'EncodingAESKey', 'Khóa mã hóa/giải mã tin nhắn công khai; khi dùng chế độ bảo mật cần điền giá trị này (lấy từ trung tâm quản lý WeChat); chỉ hỗ trợ tài khoản dịch vụ đã xác thực', ''),
(18, 10, 'Hình ảnh chia sẻ WeChat', 'Nếu điền URL ảnh này, khi chia sẻ trang sẽ dùng ảnh đó. Tránh ảnh bị méo; tỷ lệ 5:4, nên dưới 50KB', ''),
(19, 10, 'Mã QR theo dõi', 'Mã QR theo dõi công khai hiển thị khi hướng dẫn người dùng theo dõi', ''),
(21, 10, 'Tiêu đề chia sẻ WeChat', 'Tiêu đề chia sẻ WeChat', ''),
(22, 10, 'Giới thiệu chia sẻ WeChat', 'Giới thiệu chia sẻ WeChat', ''),
(25, 10, 'Mchid', 'Số merchant WeChat', ''),
(26, 10, 'WeChatThanh toánChứng chỉ', 'Chứng chỉ WeChat Pay; tải tại nền tảng merchant WeChat, tên file thường là apiclient_cert.pem', ''),
(27, 10, 'WeChatThanh toánChứng chỉKhóa', 'Khóa chứng chỉ WeChat Pay; tải tại nền tảng merchant WeChat, tên file thường là apiclient_key.pem', ''),
(28, 10, 'Key', 'Khóa bí mật thanh toán merchant. Xem trong email WeChat gửi sau khi duyệt.', ''),
(29, 10, 'WeChatThanh toán', 'Chọn kênh WeChat Pay; tắt thì phía người dùng không hiển thị', '0=>Tắt\nweixin=>WeChat\nallinpay=>Thông Liên'),
(32, 10, 'Đủ số tiền thì miễn phí vận chuyển', 'Đơn hàng đủ bao nhiêu tiền thì miễn phí vận chuyển; ưu tiên hơn cài đặt vận chuyển khác', ''),
(33, 10, 'Thanh toán tại chỗ có miễn phí vận chuyển không', 'Khi người dùng chọn thanh toán tại chỗ thì có miễn phí vận chuyển không', '1=>Miễn phí vận chuyển\n0=>Không miễn phí vận chuyển'),
(34, 10, 'Tỷ lệ đổi điểm', 'Tỷ lệ đổi điểm (1 điểm = bao nhiêu tiền), đơn vị: VND', ''),
(44, 10, 'Số tiền nạp tối thiểu', 'Số tiền nạp tối thiểu mỗi lần của người dùng', ''),
(46, 10, 'Khóa tra cứu vận chuyển', 'Khóa tra cứu vận chuyển Aliyun; mua tại: https://market.aliyun.com/products/57126001/cmapi021863.html', ''),
(49, 10, 'Tỷ lệ hoa hồng cấp 1', 'Tỷ lệ hoa hồng cho cấp trên sau khi đơn hàng thành công (0–100); ví dụ 5 = 5% giá trị đơn hàng', ''),
(53, 10, 'Số tiền rút tối thiểu', 'Hạn mức rút tiền tối thiểu của người dùng', ''),
(59, 10, 'appId', 'AppID mini app', ''),
(60, 10, 'AppSecret', 'AppSecret mini app', ''),
(61, 10, 'Địa chỉ giao diện API', 'Địa chỉ API dùng cho cấu hình tên miền máy chủ; copy nội dung ô nhập (do hệ thống tạo, không sửa)', ''),
(74, 10, 'Tên mini app', 'Tên mini app', ''),
(77, 10, 'Tồn kho cảnh báo', 'Khi tồn kho dưới bao nhiêu thì cảnh báo hết hàng', ''),
(85, 10, 'Lý do hoàn trả', 'Cấu hình lý do hoàn trả, mỗi dòng một lý do', ''),
(87, 10, 'Tỷ lệ hoa hồng cấp 2', 'Tỷ lệ hoa hồng cho cấp trên sau khi đơn hàng thành công (0–100); ví dụ 5 = 5% giá trị đơn hàng', ''),
(88, 10, 'Chế độ phân phối', 'Phân phối mọi người”Mặc địnhai cũng có thểPhân phối，“Phân phối chỉ định”chỉ có thểQuản trịthủ côngCài đặtđại lý，“Phân phối theo hạn mức”chỉ user mua đủ số tiềnSố tiềnthì tự độngBậtPhân phối', '1=>Phân phối chỉ định\n2=>Phân phối mọi người\n3=>Phân phối theo hạn mức'),
(99, 10, 'Thẻ ngân hàng rút tiền', 'Cấu hình loại thẻ ngân hàng rút tiền, mỗi ngân hàng một dòng', ''),
(108, 10, 'Loại tải lên', 'Cấu hình lưu trữ file; lưu ý: sau khi cấu hình không nên sửa, dễ gây lỗi file', '1=>Lưu trữ cục bộ\n2=>Lưu trữ Qiniu\n3=>Aliyun OSS\n4=>Tencent COS'),
(110, 10, 'Aliyun accessKey', 'accessKey lưu trữ Aliyun', ''),
(111, 10, 'Aliyun secretKey', 'secretKey lưu trữ Aliyun', ''),
(113, 10, 'Hủy đơn hàng thường chưa thanh toán', 'Thời gian tự hủy đơn hàng thường chưa thanh toán (giờ)', ''),
(114, 10, 'Hủy đơn hàng sự kiện chưa thanh toán', 'Thời gian tự hủy đơn hàng sự kiện chưa thanh toán (giờ)', ''),
(115, 10, 'Hủy đơn hàng kên giá chưa thanh toán', 'Thời gian tự hủy đơn kên giá chưa thanh toán (giờ); 0 = dùng mặc định sự kiện', ''),
(116, 10, 'Hủy đơn hàng flash sale chưa thanh toán', 'Thời gian tự hủy đơn flash sale chưa thanh toán (giờ); 0 = dùng mặc định sự kiện', ''),
(117, 10, 'Hủy đơn hàng nhóm mua chưa thanh toán', 'Thời gian tự hủy đơn nhóm mua chưa thanh toán (giờ); 0 = dùng mặc định sự kiện', ''),
(122, 10, 'Thời gian tự xác nhận nhận hàng', 'Sau khi giao hàng, nếu người dùng không bấm xác nhận thì sau N ngày tự xác nhận; 0 = không tự xác nhận (đơn vị: ngày)', ''),
(123, 10, 'AppId', 'AppId ứng dụng tạo trong tài khoản Nhất thông', ''),
(137, 10, 'AppSecret', 'AppSecret ứng dụng tạo trong tài khoản Nhất thông', ''),
(138, 10, 'Ảnh đại diện mặc định', 'Ảnh đại diện mặc định; dùng khi admin thêm user và khi user đăng nhập; kích thước 80x80', ''),
(139, 10, 'Thanh toán tại chỗ', 'Thanh toán tại chỗ: chọn bật hoặc tắt', '1=>Bật\n2=>Tắt'),
(141, 10, 'Công tắc nạp tiền mini app', 'Chỉ công tắc nạp tiền phía mini app; cần tắt trước khi gửi mini app duyệt', '1=>Bật\n0=>Tắt'),
(142, 10, 'KEY bản đồ Tencent', 'KEY bản đồ Tencent; đăng ký tại https://lbs.qq.com', ''),
(143, 10, 'Bật nhận tại cửa hàng', 'Bật thì trang đặt hàng hỗ trợ nhận tại cửa hàng; thêm điểm nhận trong Cài đặt > Giao hàng > Điểm nhận; tắt thì ẩn', '1=>Bật\n0=>Tắt'),
(145, 10, 'Công tắc in phiếu', 'In phiếu tự động khi thanh toán thành công; cần mua máy in Yi Lian Yun K4/K6 hoặc Fei E Yun V58', '1=>Bật\n0=>Tắt'),
(146, 10, 'ID nhà phát triển', 'ID người dùng trong thông tin nhà phát triển sau khi tạo ứng dụng Yi Lian Yun', ''),
(147, 10, 'Khóa bí mật ứng dụng', 'Khóa bí mật ứng dụng trong thông tin nhà phát triển Yi Lian Yun', ''),
(148, 10, 'ID ứng dụng', 'ID ứng dụng trong thông tin nhà phát triển Yi Lian Yun', ''),
(149, 10, 'Số thiết bị', 'Số thiết bị in trên nhãn máy in Yi Lian Yun', ''),
(150, 10, 'Công tắc nhắc thanh toán thành công', 'Công tắc nhắc thanh toán thành công', '0=>Tắt\n1=>Bật'),
(151, 10, 'Công tắc nhắc giao hàng', 'Công tắc nhắc giao hàng', '0=>Tắt\n1=>Bật'),
(152, 10, 'Công tắc nhắc xác nhận nhận hàng', 'Công tắc nhắc xác nhận nhận hàng', '0=>Tắt\n1=>Bật'),
(153, 10, 'Công tắc nhắc admin khi có đơn mới', 'Công tắc nhắc admin khi có đơn mới', '0=>Tắt\n1=>Bật'),
(154, 10, 'Công tắc nhắc admin khi thanh toán thành công', 'Công tắc nhắc admin khi thanh toán thành công', '0=>Tắt\n1=>Bật'),
(155, 10, 'Công tắc nhắc admin khi hoàn tiền', 'Công tắc nhắc admin khi hoàn tiền', '0=>Tắt\n1=>Bật'),
(156, 10, 'Nhắc admin bằng SMS khi người dùng xác nhận nhận hàng', 'Nhắc admin bằng SMS khi người dùng xác nhận nhận hàng', '0=>Tắt\n1=>Bật'),
(158, 10, 'Lưu ý khi nạp tiền', 'Lưu ý khi nạp tiền', ''),
(159, 10, 'Thời gian đóng băng hoa hồng', 'Tránh người dùng hoàn tiền trong khi đã rút hoa hồng; cần đặt thời gian đóng băng hoa hồng (ngày)', ''),
(160, 10, 'Số tiền tối thiểu phân phối theo hạn mức', 'Phân phối theo hạn mức: đủ số tiền thì được quyền phân phối', ''),
(162, 10, 'Công tắc nhắc SMS khi đổi giá', 'Công tắc nhắc SMS khi đổi giá', '0=>Tắt\n1=>Bật'),
(168, 10, 'LOGO nhỏ quản trị', 'Logo nhỏ thu menu quản trị; kích thước 180x180', ''),
(170, 10, 'Thanh toán bằng số dư', 'Thanh toán bằng số dư: chọn bật hoặc tắt', '1=>Bật\n2=>Tắt'),
(171, 10, 'LOGO trang đăng nhập quản trị', 'Logo trang đăng nhập quản trị; kích thước khuyến nghị 270x75', ''),
(173, 10, 'accessKey', 'accessKey Qiniu', ''),
(174, 10, 'secretKey', 'secretKey Qiniu', ''),
(178, 10, 'accessKey', 'accessKey Tencent Cloud', ''),
(179, 10, 'secretKey', 'secretKey Tencent Cloud', ''),
(187, 10, '99Api apiKey', 'Đăng ký 99api, copy key tại trung tâm cá nhân', ''),
(189, 10, 'Bật chức năng số dư', 'Bật hoặc tắt chức năng số dư trong cửa hàng', '1=>Bật\n0=>Tắt\n'),
(190, 10, 'Bật phân phối', 'Bật/tắt chức năng phân phối', '1=>Bật\n0=>Tắt'),
(191, 10, 'Tặng điểm khi đặt hàng', 'Tặng điểm theo tỷ lệ tiền thanh toán (1 đơn vị tiền = bao nhiêu điểm)', ''),
(193, 10, 'Bật cấp người dùng', 'Bật/tắt chức năng cấp người dùng', '1=>Bật\n0=>Tắt'),
(194, 10, 'Giá hội viên trả phí sản phẩm', 'Có hiển thị giá hội viên trả phí cho sản phẩm không', '1=>Bật\n0=>Tắt'),
(195, 10, 'Bắt buộc đăng nhập bằng SĐT', 'Sau khi ủy quyền, bắt buộc bind SĐT để đồng bộ nhiều thiết bị', '1=>Bắt buộc\n0=>Không bắt buộc'),
(196, 10, 'Tặng kinh nghiệm khi đặt hàng', 'Tỷ lệ tặng kinh nghiệm khi đặt hàng (1 đơn vị tiền = bao nhiêu kinh nghiệm)', ''),
(198, 10, 'Tặng kinh nghiệm khi điểm danh', 'Tặng kinh nghiệm khi điểm danh', ''),
(199, 10, 'Tặng kinh nghiệm khi mời user mới', 'Mời một người dùng mới được tặng kinh nghiệm', ''),
(200, 10, 'Liên kết quan hệ phân phối', 'Tất cả user”chỉ user không có đại lý cấp trên;user bấm hoặc quét mã đại lý để liên kếtquan hệ phân phối; "User mới": user mới đăng ký hoặc lần đầu vào hệ thống mới được liên kết', '1=>Tất cả user\n2=>User mới'),
(235, 10, 'Công tắc nhắc SMS đơn chưa thanh toán', 'Công tắc nhắc SMS đơn chưa thanh toán', '1=>Bật\n0=>Tắt'),
(236, 10, 'Thời hạn mã xác thực', 'Thời gian hết hạn mã SMS (phút)', ''),
(246, 10, 'Bật chức năng hóa đơn', 'Bật/tắt chức năng hóa đơn', '1=>Bật\n0=>Tắt'),
(247, 10, 'Bật hóa đơn chuyên dụng', 'Bật/tắt hóa đơn chuyên dụng', '1=>Bật\n0=>Tắt'),
(287, 10, 'Thanh toán Alipay', 'Chọn kênh Alipay; tắt thì phía user không hiển thị', '0=>Tắt\nalipay=>Alipay\nallinpay=>Thông Liên'),
(288, 10, 'Khóa công khai Alipay', 'Khóa công khai Alipay sau khi hoàn tất ký Alipay', ''),
(289, 10, 'Khóa riêng ứng dụng thanh toán', 'Khóa riêng ứng dụng thanh toán', ''),
(290, 10, 'Appid ứng dụng thanh toán', 'Appid ứng dụng thanh toán', ''),
(291, 10, 'Chọn giao diện', 'Khuyến nghị dùng Nhất thông, không cần cấu hình khóa; link mua Aliyun: https://market.aliyun.com/...：https://market.aliyun.com/apimarket/detail/cmapi021863', '1=>Nhất thông\n2=>Aliyun tra cứu vận chuyển'),
(292, 10, 'Chọn giao diện', 'Chọn giao diện thu thập sản phẩm; Nhất thông đăng ký nhanh, kích hoạt dùng không cần cấu hình apikey; hoặc truy cập https://www.99api.com/ đăng ký tài khoản; khuyến nghị Nhất thông tiện lợi.', '1=>Nhất thông\n2=>99Api'),
(299, 10, 'Công ty vận chuyển', 'Công ty vận chuyển', ''),
(300, 10, 'Mẫu vận chuyển', 'Mẫu vận chuyển', ''),
(301, 10, 'Tên người gửi', 'Tên người gửi trên phiếu gửi hàng', ''),
(302, 10, 'Số điện thoại người gửi', 'Số điện thoại người gửi trên phiếu', ''),
(303, 10, 'Địa chỉ chi tiết người gửi', 'Địa chỉ chi tiết người gửi trên phiếu', ''),
(304, 10, 'Số máy in', 'Mua máy in mây KX100L3 (ví dụ Kuaidi 100 thế hệ 2)', ''),
(305, 10, 'Phản hồi chăm sóc khách hàng', 'Chữ hiển thị khi chuyển tới trang phản hồi khi chưa có CSKH trực tuyến', ''),
(307, 10, 'Giới hạn điểm tối đa mỗi đơn', 'Giới hạn điểm dùng mỗi đơn; 0 = không giới hạn', ''),
(310, 10, 'Bật hội viên trả phí', 'Công tắc hội viên trả phí', '1=>Bật\n0=>Tắt'),
(324, 10, 'Ảnh poster phân phối', 'Ảnh poster phân phối trong trang cá nhân; kích thước 600x1000', ''),
(325, 10, 'Bật phiếu điện tử', 'Có bật phiếu điện tử không; sau khi bật vui lòng cấu hình <a href="/admin/setting/freight/express/index">tài khoản trả theo tháng</a> trong danh sách đơn vị vận chuyển', '1=>Bật\n0=>Tắt'),
(326, 10, 'Logo đăng nhập phiên bản mobile', 'Logo đăng nhập phiên bản mobile; kích thước 86x86, định dạng PNG', ''),
(327, 10, 'Logo phiên bản PC', 'Logo phiên bản PC', ''),
(328, 10, 'Số đăng ký website', 'Số đăng ký website; hiển thị ở chân H5 và PC', ''),
(329, 10, 'Loại CSKH', 'Theo hệ thống: dùng CSKH mặc định, gọi điện hoặc chuyển link; Mini app: cần cấu hình user CSKH trong quản lý Mini app.', '0=>Theo hệ thống\n1=>CSKH Mini app'),
(330, 10, 'Bật trang', 'Bật hoặc tắt trang (dùng khi nâng cấp tạm thời); khi tắt, giao diện sẽ hiện popup "Trang đang nâng cấp, vui lòng quay lại sau".', '1=>Bật\n0=>Tắt'),
(331, 10, 'Đơn giá hoa hồng giới thiệu', 'Đơn giá hoa hồng giới thiệu (mỗi user được giới thiệu)', ''),
(332, 10, 'Hạn mức hoa hồng giới thiệu mỗi ngày', 'Hạn mức hoa hồng giới thiệu mỗi ngày (0: không phát; -1: không giới hạn; nên là bội số của đơn giá)', ''),
(333, 10, 'Hoa hồng tự mua', 'Có bật hoa hồng tự mua không (Bật: đại lý tự mua hàng được hưởng hoa hồng cấp 1, cấp trên hưởng cấp 2; Tắt: đại lý tự mua không có hoa hồng).', '1=>Bật\n0=>Tắt'),
(334, 10, 'Chế độ liên kết', 'Vĩnh viễn”một lần liên kếtcó hiệu lực vĩnh viễn，“Có hiệu lực”sau khi liên kết có hiệu lực trong N ngày，“Tạm thời” có hiệu lực tạm thời', '1=>Vĩnh viễn\n2=>Có hiệu lực\n3=>Tạm thời'),
(335, 10, 'Hiệu lực liên kết', 'Hiệu lực liên kết (trong N ngày sau khi liên kết)', ''),
(336, 10, 'Tên người nhận hàng hoàn trả', 'Sau khi user yêu cầu hoàn trả và quản trị đồng ý, hiển thị tên người nhận hàng hoàn trong chi tiết đơn hoàn trả.', ''),
(337, 10, 'SĐT người nhận hàng hoàn trả', 'Sau khi user yêu cầu hoàn trả và quản trị đồng ý, hiển thị SĐT người nhận trong chi tiết đơn hoàn trả.', ''),
(338, 10, 'Địa chỉ nhận hàng hoàn trả', 'Sau khi user yêu cầu hoàn trả và quản trị đồng ý, hiển thị địa chỉ nhận hàng hoàn trong chi tiết đơn hoàn trả.', ''),
(339, 10, 'Hoa hồng user giới thiệu', 'User được giới thiệu nhận hoa hồng', '1=>Bật\n0=>Tắt'),
(340, 10, 'AppID', 'AppID do nền tảng mở WeChat cấp sau khi đăng ký ứng dụng web', ''),
(341, 10, 'AppSecret', 'AppSecret do nền tảng mở WeChat cấp sau khi đăng ký ứng dụng web', ''),
(342, 10, 'Số điện thoại liên hệ', 'Số điện thoại hiển thị ở chân trang PC', ''),
(343, 10, 'Địa chỉ công ty', 'Địa chỉ công ty hiển thị ở chân trang PC', ''),
(345, 10, 'Từ khóa', 'Từ khóa website', ''),
(346, 10, 'Mô tả website', 'Mô tả website', ''),
(347, 10, 'Loại mã QR', 'Mã công khai hoặc mã mini app hiển thị khi mua trên điện thoại tại trang chi tiết sản phẩm', '1=>Công khai\n2=>Mini app'),
(348, 10, 'Số mục đề xuất', 'Số mục sản phẩm đề xuất trên trang chủ', ''),
(349, 10, 'Số mục hàng mới', 'Số mục hàng mới ra mắt trên trang chủ', ''),
(350, 10, 'Loại CSKH', 'CSKH hệ thống: dùng CSKH tích hợp; Gọi điện: bấm gọi SĐT CSKH; Liên kết: chuyển tới link ngoài', '0=>CSKH hệ thống\n1=>Gọi điện\n2=>Chuyển link'),
(351, 10, 'Link CSKH', 'Khi chọn loại CSKH là chuyển link thì điền URL', ''),
(352, 10, 'SĐT CSKH', 'Khi chọn gọi điện thì điền SĐT khi user bấm liên hệ CSKH', ''),
(353, 10, 'APPID', 'APPID do nền tảng mở WeChat cấp cho ứng dụng mobile', ''),
(354, 10, 'AppSecret', 'AppSecret do nền tảng mở WeChat cấp cho ứng dụng mobile', ''),
(355, 10, 'JS tùy chỉnh phiên bản mobile', 'JS tùy chỉnh tải trên phiên bản mobile', ''),
(359, 10, 'File xác thực WeChat', 'File xác thực WeChat tải khi cấu hình tên miền ủy quyền web; tải lên tại đây', ''),
(360, 10, 'Ảnh thu nhỏ lớn (px): rộng', 'Ảnh thu nhỏ lớn (px): rộng', ''),
(361, 10, 'Ảnh thu nhỏ lớn (px): cao', 'Ảnh thu nhỏ lớn (px): cao', ''),
(362, 10, 'Ảnh thu nhỏ vừa (px): rộng', 'Ảnh thu nhỏ vừa (px): rộng', ''),
(363, 10, 'Ảnh thu nhỏ vừa (px): cao', 'Ảnh thu nhỏ vừa (px): cao', ''),
(364, 10, 'Ảnh thu nhỏ nhỏ (px): rộng', 'Ảnh thu nhỏ nhỏ (px): rộng', ''),
(365, 10, 'Ảnh thu nhỏ nhỏ (px): cao', 'Ảnh thu nhỏ nhỏ (px): cao', ''),
(366, 10, 'Có bật watermark không', 'Có bật watermark ảnh không', '1=>Bật\n0=>Tắt'),
(367, 10, 'Loại watermark', 'Loại watermark：Hình ảnh、Chữ', '1=>Hình ảnh\n2=>Chữ'),
(368, 10, 'Ảnh watermark', 'Link ảnh watermark', ''),
(369, 10, 'Vị trí watermark', 'watermark_position', '1=>Trên trái\n2=>Trên giữa\n3=>Trên phải\n4=>Giữa trái\n5=>Giữa\n6=>Giữa phải\n7=>Dưới trái\n8=>Dưới giữa\n9=>Dưới phải'),
(370, 10, 'Độ trong suốt ảnh watermark', 'Độ trong suốt ảnh watermark', ''),
(371, 10, 'Độ nghiêng ảnh watermark', 'Độ nghiêng ảnh watermark', ''),
(372, 10, 'Chữ watermark', 'Chữ watermark', ''),
(373, 10, 'Cỡ chữ watermark (px)', 'Cỡ chữ watermark (px)', ''),
(374, 10, 'Màu chữ watermark', 'Màu chữ watermark', ''),
(375, 10, 'Góc xoay chữ watermark', 'Góc xoay chữ watermark', ''),
(376, 10, 'Lệch hoành độ watermark (px)', 'Lệch hoành độ watermark (px)', ''),
(377, 10, 'Lệch tung độ watermark (px)', 'Lệch tung độ watermark (px)', ''),
(379, 10, 'Icon ICO hệ thống', 'Icon ICO chương trình; sau khi đổi cần xóa cache trình duyệt', ''),
(383, 10, 'TencentAPPID', 'TencentAPPID', ''),
(384, 10, 'Cách thức rút tiền', 'Bật thì user mới chọn được phương thức rút tiền này', '0=>Thẻ ngân hàng\n1=>WeChat\n2=>Alipay\n3=>Số dư'),
(385, 10, 'Đóng băng điểm (ngày)', 'Đóng băng điểm (ngày); 0 = không đóng băng', ''),
(386, 10, 'Chọn nền tảng', 'Chọn nền tảng in', '1=>Yi Lian Yun\n2=>Fei E Yun'),
(387, 10, 'Loại phiếu điện tử', 'Loại phiếu điện tử', '1=>Nhất thông'),
(388, 10, 'ID doanh nghiệp', 'Nếu link CSKH là WeChat doanh nghiệp và mini app cần chuyển tới đó thì cấu hình mục này và liên kết ID doanh nghiệp trong CSKH mini app', ''),
(389, 10, 'Theo dõi có tạo user cửa hàng không', 'Sau khi user theo dõi công khai có tạo user cửa hàng không', '1=>Bật\n0=>Tắt'),
(390, 10, 'Trả hộ bạn bè', 'Công tắc trả hộ; tắt thì không hiển thị lựa chọn trả hộ', '1=>Bật\n0=>Tắt'),
(392, 10, 'Cấp phân phối', 'Cấp phân phối: cấp 1 chỉ hoa hồng cho cấp trên trực tiếp; cấp 2 gồm cấp trên và cấp trên nữa', '1=>Phân phối cấp 1\n2=>Phân phối cấp 2'),
(393, 10, 'SMSLoại', 'Loại SMS; chọn loại SMS gửi đi', '0=>Nhất thông\n1=>Aliyun\n2=>Tencent'),
(394, 10, 'AccessKeyId', 'AccessKeyId Aliyun', ''),
(395, 10, 'AccessKeySecret', 'AccessKeySecret Aliyun', ''),
(396, 10, 'RegionId', 'RegionId Aliyun', ''),
(397, 10, 'Chữ ký SMS', 'Chữ ký SMS', ''),
(398, 10, 'SKD AppID', 'Tencent SMS SDK APPID', ''),
(399, 10, 'AccessKeyId', 'TencentAccessKeyId', ''),
(400, 10, 'AccessKeySecret', 'TencentAccessKeySecret', ''),
(401, 10, 'TencentChữ ký SMS', 'TencentChữ ký SMS', ''),
(402, 10, 'Vùng SMS', 'Vùng SMS: điền một trong ap-beijing, ap-guangzhou, ap-nanjing', ''),
(409, 10, 'Chọn số merchant Mini app', 'Quản trị Mini app có quản lý thanh toán thì chọn không liên kết số merchant', '0=>Liên kết số merchant\n1=>Không liên kết số merchant'),
(410, 10, 'Số merchant thanh toán Mini app', 'Số merchant do mini app tạo khi bật quản lý thanh toán', ''),
(411, 10, 'Thời gian tự đánh giá', 'Sau khi nhận hàng, nếu user không đánh giá thì sau N ngày tự đánh giá; 0 = không tự đánh giá', ''),
(412, 10, 'Nội dung đánh giá tự động', 'Chữ đánh giá tự động hiển thị', ''),
(413, 10, 'Loại giao diện thanh toán', 'Loại API thanh toán: v2 = WeChat Pay phiên bản cũ; v3 = WeChat Pay v3; chứng chỉ dùng chung được; khóa v3 khác v2', '0=>v2 (Hỗ trợ chuyển doanh nghiệp tới ví lẻ)\n1=>v3 (Hỗ trợ chuyển merchant tới ví lẻ)'),
(414, 10, 'Số seri chứng chỉ', 'Số seri của "Chứng chỉ API Merchant", có thể xem trong quản lý chứng chỉ', ''),
(415, 10, 'V3Thanh toánKey', 'Khóa bí mật thanh toán V3', ''),
(416, 10, 'Tặng số dư (đơn vị tiền)', 'Tiền thưởng user mới; ≥0; 0 = không tặng', ''),
(417, 10, 'Tặng điểm', 'Điểm thưởng user mới; ≥0; 0 = không tặng', ''),
(418, 10, 'AccessKey', 'Dịch máy chỉ hỗ trợ Volcano; đăng ký https://console.volcengine.com, tạo API key trong Access Control', ''),
(419, 10, 'SecretKey', 'Dịch máy chỉ hỗ trợ Volcano; đăng ký https://console.volcengine.com, tạo API key trong Access Control', ''),
(420, 10, 'Fei E Yun USER', 'Tài khoản đăng ký trên quản trị Fei E Yun', ''),
(421, 10, 'Fei E Yun UKEY', 'UKEY do quản trị Fei E Yun tạo sau khi đăng ký (ghi chú: không điền KEY máy in)', ''),
(422, 10, 'Fei E Yun SN', 'Mã trên nhãn máy in; cần thêm máy in trong quản trị hoặc gọi API thêm trước khi gọi in', ''),
(423, 10, 'Khóa MD5 Thông Liên', 'Khóa MD5 thanh toán Thông Liên, cấu hình trong Cài đặt quản trị Merchant', ''),
(425, 10, 'Số merchant Thông Liên', 'Số merchant Thông Liên do công ty bạn đăng ký', ''),
(426, 10, 'Appid thanh toán Thông Liên', 'Xem trong Cài đặt quản trị Merchant Thông Liên, mục Đối tiếp', ''),
(428, 10, 'Message queue', 'Có bật message queue không; bật giúp chạy nhanh hơn; cần cấu hình Redis trước; tài liệu: https://doc.crmeb.com/...', '1=>Bật\n0=>Tắt'),
(429, 10, 'Bắt buộc lấy tên và avatar', 'Sau khi user mini app ủy quyền có hiện popup lấy nickname và avatar không', '1=>Bật\n0=>Tắt'),
(430, 10, 'Loại mã giới thiệu công khai', 'Loại mã giới thiệu công khai: Cửa hàng: quét vào cửa hàng; Công khai: quét vào công khai rồi đẩy link cửa hàng', '0=>Cửa hàng\n1=>Công khai'),
(431, 10, 'Hoa hồng mua hội viên trả phí', 'Mua hội viên trả phí có tính hoa hồng theo tỷ lệ cài đặt không', '1=>Bật\n0=>Tắt'),
(432, 10, 'Loại hoa hồng', 'Chọn loại hoa hồng: theo giá bán sản phẩm (tính theo giá bán) hoặc theo giá thanh toán thực tế (tính theo giá thanh toán thực tế)', '0=>Theo giá sản phẩm\n1=>Theo giá thanh toán thực tế'),
(433, 10, 'Đăng ký an ninh mạng', 'Thông tin đăng ký với công an; hiển thị ở chân PC và H5', ''),
(435, 10, 'Link đăng ký ICP', 'Link khi bấm vào số đăng ký ICP ở chân H5/PC', ''),
(436, 10, 'Link đăng ký an ninh mạng', 'Link khi bấm vào số đăng ký an ninh mạng ở chân H5/PC', ''),
(438, 10, 'Quản lý thông tin giao hàng', 'Nếu mini app có quản lý giao hàng đơn thì bật công tắc này, không sẽ đóng băng tiền đơn', '1=>Bật\n0=>Tắt'),
(440, 10, 'accessKey JD Cloud', 'accessKey JD Cloud', ''),
(441, 10, 'secretKey JD Cloud', 'secretKey JD Cloud', ''),
(442, 10, 'accessKey Huawei Cloud', 'accessKey Huawei Cloud', ''),
(443, 10, 'secretKey Huawei Cloud', 'secretKey Huawei Cloud', ''),
(444, 10, 'secretKey Tianyi Cloud', 'secretKey Tianyi Cloud', ''),
(445, 10, 'accessKey Tianyi Cloud', 'accessKey Tianyi Cloud', ''),
(446, 10, 'Trạng thái hoàn trả phiếu giảm giá', 'Có trả lại phiếu giảm giá khi hoàn tiền không', '1=>Hoàn trả\n0=>Không hoàn trả'),
(447, 10, 'storageRegion JD Cloud', 'storageRegion JD Cloud', ''),
(449, 10, 'Công tắc điểm danh', 'Công tắc điểm danh; tắt thì ẩn lối vào điểm danh', '1=>Bật\n0=>Tắt'),
(450, 10, 'Chế độ điểm danh', 'Không giới hạn: điểm danh tích lũy và liên tục không bị xóa; Theo tuần: mỗi thứ hai xóa về 0 và tính lại; Theo tháng: mùng 1 mỗi tháng xóa về 0 và tính lại', '-1=>Không giới hạn\n1=>Theo tuần\n0=>Theo tháng'),
(451, 10, 'Nhắc điểm danh', 'Có bật nhắc điểm danh không; nhắc qua SMS và tin nội bộ', '1=>Bật\n0=>Tắt'),
(452, 10, 'Thời gian nhắc', 'Chọn thời gian nhắc mỗi ngày chưa điểm danh', ''),
(453, 10, 'Cách nhắc', 'Cách nhắc điểm danh hằng ngày: SMS hoặc tin nội bộ', '1=>SMS\n2=>Tin nội bộ'),
(454, 10, 'Điểm tặng khi điểm danh', 'Điểm tặng khi điểm danh mỗi ngày', ''),
(455, 10, 'Loại merchant', 'Loại merchant: merchant WeChat thường hoặc nhà cung cấp dịch vụ WeChat', '0=>Chế độ merchant WeChat Pay\n1=>Chế độ đại lý WeChat Pay'),
(456, 10, 'Số merchant con', 'Số merchant con của nhà cung cấp WeChat Pay', ''),
(457, 10, 'Phí rút tiền', 'Phần trăm phí rút tiền (0–100); 0 = không phí; ví dụ 10%: rút 100 còn 90', ''),
(458, 10, 'Cách lấy số điện thoại', 'Cách mini app lấy SĐT: ủy quyền WeChat hoặc nhập mã xác thực SĐT', '1=>Ủy quyền WeChat\n2=>Nhập thủ công'),
(460, 10, 'Thời hạn bảo hành / hoàn tiền', 'Sau khi nhận hàng, trong bao nhiêu ngày được hoàn tiền; quá ngày thì ẩn nút hoàn tiền; 0 = luôn hiển thị', ''),
(461, 10, 'Địa chỉ API', 'Địa chỉ API dùng cho push tin nhắn mini app; copy từ ô nhập (do hệ thống tạo)', ''),
(462, 10, 'Token xác thực Mini app', 'Token xác thực Mini app', ''),
(463, 10, 'Cách thức mã hóa/giải mã tin nhắn', 'Cách mã hóa tin nhắn push mini app; hiện chỉ hỗ trợ chế độ văn bản rõ', '0=>Chế độ văn bản rõ\n1=>Chế độ tương thích\n2=>Chế độ bảo mật'),
(464, 10, 'EncodingAESKey', 'Khóa mã hóa tin nhắn gồm 43 ký tự A-Z, a-z, 0-9', ''),
(465, 10, 'Cấu hình module', 'Cấu hình module; chọn thì hiển thị module tương ứng; bỏ chọn thì ẩn', 'seckill=>Flash sale\nbargain=>Kên giá\ncombination=>Nhóm mua'),
(466, 10, 'APPID merchant chính', 'Khi bật thanh toán đại lý, cần cấu hình APPID công khai dịch vụ do merchant chính đăng ký khi mở', ''),
(467, 10, 'Công tắc cửa sổ nổi hoa hồng', 'Công tắc cửa sổ nổi hoa hồng; tắt thì trang chi tiết sản phẩm không hiện', '1=>Bật\n0=>Tắt'),
(468, 10, 'Trạng thái hóa đơn điện tử', 'Có bật hóa đơn điện tử không', '1=>Bật\n0=>Tắt'),
(469, 10, 'Tự động xuất hóa đơn', 'Có bật tự động xuất hóa đơn không', '1=>Bật\n0=>Tắt'),
(470, 10, 'Phân loại hóa đơn điện tử', 'Phân loại sản phẩm cho hóa đơn điện tử', ''),
(471, 10, 'Thuế suất hóa đơn điện tử', 'Điền thuế suất hóa đơn điện tử (0–100), ví dụ 13% điền 13', ''),
(472, 10, 'Tên phân loại hóa đơn', 'Tên phân loại hóa đơn điện tử dùng để hiển thị', ''),
(473, 10, 'Địa chỉ đăng nhập từ xa', 'Khi link H5 nhúng cửa hàng có tham số remote_token thì tự đăng nhập; nếu không có token thì chuyển tới địa chỉ này để đăng nhập', ''),
(474, 10, 'WAFCấu hình', 'Tham số kiểm tra cấu hình WAF; lọc bỏ tham số không cần hoặc chặn request; nhiều tham số cách nhau bằng xuống dòng', ''),
(475, 10, 'Duyệt đánh giá', 'Đánh giá sản phẩm do user gửi có cần quản trị duyệt không; có thì hiển thị sau khi duyệt, không thì hiển thị ngay sau khi gửi', '1=>Cần duyệt\n0=>Không cần duyệt'),
(476, 10, 'Tặng phiếu giảm giá', 'Tặng phiếu giảm giá', ''),
(477, 10, 'WAFLoại', 'WAFLoại: Tắt (mọi tham số đều qua); Chặn (chặn request khớp WAF); Lọc (bỏ tham số khớp WAF rồi cho qua)', '0=>Tắt\n1=>Chặn\n2=>Lọc'),
(478, 10, 'Cấu hình loại sản phẩm', 'Cấu hình loại sản phẩm khi thêm sản phẩm', '0=>Sản phẩm thường\n1=>Mã thẻ / Ổ đĩa mạng\n2=>Phiếu giảm giá\n3=>Sản phẩm ảo'),
(479, 10, 'WeChatRút tiền', 'WeChatRút tiềnCách: Chuyển khoản thủ công; Tự động chuyển vào ví lẻ (cần bật chuyển merchant tới ví lẻ)', '0=>Chuyển khoản thủ công\n1=>Tự động chuyển vào ví lẻ'),
(480, 10, 'AlipayRút tiền', 'AlipayRút tiềnCách: Chuyển khoản thủ công; Tự động chuyển vào số dư (cần bật chuyển Alipay)', '0=>Chuyển khoản thủ công\n1=>Tự động chuyển vào số dư'),
(481, 10, 'Khóa công khai thanh toán v3', 'Khóa công khai thanh toán v3; điền nếu dùng phiên bản mới', ''),
(482, 10, 'Chứng chỉ khóa công khai thanh toán v3', 'Chứng chỉ khóa công khai v3; tải lên khi dùng khóa công khai mới', ''),
(483, 10, 'Giá trị scene rút tiền tự động WeChat', 'Giá trị scene rút tiền tự động WeChat', ''),
(484, 10, 'JS tùy chỉnh quản trị', 'JS tùy chỉnh tải ở quản trị', ''),
(485, 10, 'JS tùy chỉnh PC', 'JS tùy chỉnh tải ở PC', ''),
(486, 10, 'Chứng chỉ khóa công khai ứng dụng', 'Chứng chỉ khóa công khai ứng dụng tải sau khi hoàn tất ký giao diện Alipay', ''),
(487, 10, 'Chứng chỉ khóa công khai Alipay', 'Chứng chỉ khóa công khai Alipay tải sau khi ký', ''),
(488, 10, 'Chứng chỉ gốc Alipay', 'Chứng chỉ gốc Alipay tải sau khi ký', ''),
(489, 10, 'Loại ký giao diện', 'Loại ký giao diện: Khóa hoặc Chứng chỉ', '0=>Khóa\n1=>Chứng chỉ'),
(490, 10, 'Công tắc ảnh thu nhỏ', 'Có bật ảnh thu nhỏ không', '1=>Bật\n0=>Tắt')
ON DUPLICATE KEY UPDATE `info` = VALUES(`info`), `desc` = VALUES(`desc`), `parameter` = VALUES(`parameter`);
