<?php
// +----------------------------------------------------------------------
// | CRMEB [ CRMEBTrao quyền cho các nhà phát triển và giúp doanh nghiệp phát triển ]
// +----------------------------------------------------------------------
// | Copyright (c) 2016~2026 https://www.crmeb.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed CRMEBĐây không phải là phần mềm miễn phí và không thể xóa bản quyền liên quan đến CRMEB nếu không được phép.
// +----------------------------------------------------------------------
// | Author: CRMEB Team <admin@crmeb.com>
// +----------------------------------------------------------------------

namespace crmeb\utils;

/**
 * Map nhãn DIY/theme (legacy tiếng Trung / dịch máy) sang tiếng Việt.
 * Dùng khi đọc JSON theme/DIY. Sau khi chạy vn_diy_label_migration.sql (Phase 6),
 * DB là nguồn chính; class này chỉ fallback cho bản ghi JSON còn sót.
 */
class DiyHomeLabelMap
{
    public static function exactMap(): array
    {
        return [
            'Trang chủ' => 'Trang chủ',
            '模板' => 'Mẫu',
            '标题' => 'Tiêu đề',
            '链接' => 'Liên kết',
            '文字' => 'Văn bản',
            '图片' => 'Hình ảnh',
            '更多' => 'Thêm',
            '商城头条' => 'Tin nổi bật',
            '商品Danh mục' => 'Danh mục sản phẩm',
            '新闻资讯' => 'Tin tức',
            '领优惠券' => 'Nhận mã giảm giá',
            '浏览记录' => 'Lịch sử xem',
            '积分商城' => 'Cửa hàng điểm',
            '疯狂砍价' => 'Săn deal giá sốc',
            '低至0元免费拿' => 'Giá từ 0đ',
            '超值拼团' => 'Ghép nhóm tiết kiệm',
            '限时秒杀' => 'Flash sale',
            '签到' => 'Điểm danh',
            '优惠券' => 'Mã giảm giá',
            '文章列表' => 'Danh sách bài viết',
            '新闻公告' => 'Thông báo',
            '导航组' => 'Nhóm điều hướng',
            '轮播搜索' => 'Banner tìm kiếm',
            '底部导航' => 'Điều hướng dưới',
            '商品列表' => 'Danh sách sản phẩm',
            '官方动态' => 'Tin chính thức',
            '样式一' => 'Kiểu 1',
            '样式二' => 'Kiểu 2',
            '显示' => 'Hiển thị',
            '隐藏' => 'Ẩn',
            '选择风格' => 'Chọn kiểu',
            '色调' => 'Tông màu',
            '加粗' => 'Đậm',
            '正常' => 'Bình thường',
            '倾斜' => 'Nghiêng',
            '上传图片' => 'Tải ảnh lên',
            '背景颜色' => 'Màu nền',
            '背景设置' => 'Thiết lập nền',
            '背景圆角' => 'Bo góc nền',
            '标题图片' => 'Ảnh tiêu đề',
            '右侧按钮' => 'Nút bên phải',
            '按钮字号' => 'Cỡ chữ nút',
            '按钮效果' => 'Hiệu ứng nút',
            '按钮样式' => 'Kiểu nút',
            '按钮颜色' => 'Màu nút',
            '文字颜色' => 'Màu chữ',
            '分割线' => 'Đường phân cách',
            '内容设置' => 'Thiết lập nội dung',
            '显示内容' => 'Nội dung hiển thị',
            '商品样式' => 'Kiểu sản phẩm',
            '头部样式' => 'Kiểu đầu trang',
            '两列展示' => 'Hiển thị 2 cột',
            '两列纵向' => '2 cột dọc',
            '单列展示' => 'Hiển thị 1 cột',
            '三列展示' => 'Hiển thị 3 cột',
            '左右滑动' => 'Vuốt trái phải',
            '大图展示' => 'Hiển thị ảnh lớn',
            '商品数量' => 'Số lượng sản phẩm',
            '展示信息' => 'Thông tin hiển thị',
            '商品标签' => 'Nhãn sản phẩm',
            '商品排序' => 'Sắp xếp sản phẩm',
            '综合' => 'Tổng hợp',
            '销量' => 'Doanh số',
            '价格' => 'Giá',
            '商品销量' => 'Số lượng đã bán',
            '商品评分' => 'Đánh giá sản phẩm',
            '会员价格' => 'Giá thành viên',
            '评分颜色' => 'Màu đánh giá',
            'Giỏ hàng按钮' => 'Nút giỏ hàng',
            '进入商品详情页' => 'Vào trang chi tiết sản phẩm',
            '商品加购' => 'Thêm mới giỏ',
            '选择方式' => 'Cách chọn',
            '指定商品' => 'Chỉ định sản phẩm',
            '指定Danh mục' => 'Chỉ định danh mục',
            '指示器样式' => 'Kiểu chỉ báo',
            '指示器位置' => 'Vị trí chỉ báo',
            '左对齐' => 'Căn trái',
            '居中对齐' => 'Căn giữa',
            '右对齐' => 'Căn phải',
            '样式三' => 'Kiểu 3',
            '样式四' => 'Kiểu 4',
            '横向' => 'Ngang',
            '纵向' => 'Dọc',
            '左斜' => 'Nghiêng trái',
            '右斜' => 'Nghiêng phải',
            '渐变方向' => 'Hướng chuyển màu',
            '内边距' => 'Khoảng đệm trong',
            '外边距' => 'Khoảng đệm ngoài',
            '边框设置' => 'Thiết lập viền',
            '边框样式' => 'Kiểu viền',
            '实线' => 'Nét liền',
            '虚线' => 'Nét đứt',
            '点状' => 'Chấm',
            '边框粗细' => 'Độ dày viền',
            '边框颜色' => 'Màu viền',
            '阴影设置' => 'Thiết lập bóng',
            '阴影颜色' => 'Màu bóng',
            '模糊半径' => 'Bán kính mờ',
            '扩展半径' => 'Bán kính mở rộng',
            '建议尺寸' => 'Kích thước gợi ý',
            '图片尺寸' => 'Kích thước ảnh',
            '填写内容' => 'Nhập nội dung',
            '设置' => 'Thiết lập',
            '显示时间' => 'Thời gian hiển thị',
            '爆款热卖' => 'Bán chạy',
            '秒杀介绍' => 'Giới thiệu flash sale',
            '商品选项卡' => 'Tab sản phẩm',
            '选中文字' => 'Chữ được chọn',
        ];
    }

    public static function partialMap(): array
    {
        return [
            '展示设置' => 'Thiết lập hiển thị',
            '搜索设置' => 'Thiết lập tìm kiếm',
            '搜索热词' => 'Từ khóa hot',
            '选项卡设置' => 'Thiết lập tab',
            '图片设置' => 'Thiết lập hình ảnh',
            '标签设置' => 'Thiết lập nhãn',
            '指示器设置' => 'Thiết lập chỉ báo',
            '渐变设置' => 'Thiết lập chuyển màu',
            'Danh mục设置' => 'Thiết lập phân loại',
            '定位类型' => 'Kiểu định vị',
            '门店' => 'Cửa hàng',
            '用户定位' => 'Định vị người dùng',
            '搜索框' => 'Ô tìm kiếm',
            '滚动至顶部固定' => 'Cuộn lên đầu thì cố định',
            '正常显示' => 'Hiển thị bình thường',
            '设置搜索热词显示时间' => 'Thời gian hiển thị từ khóa hot',
            '滚动时间' => 'Thời gian cuộn',
            '鼠标拖拽版块可调整选项卡顺序' => 'Kéo thả để sắp xếp thứ tự tab',
            '显示文字' => 'Chữ hiển thị',
            '数据类型' => 'Loại dữ liệu',
            '微页面' => 'Vi trang',
            '商品Danh mục' => 'Danh mục sản phẩm',
            '组件背景' => 'Nền thành phần',
            '选中样式' => 'Kiểu đã chọn',
            '常规样式' => 'Kiểu thường',
            '图片圆角' => 'Bo góc ảnh',
            '全部' => 'Tất cả',
            '单个' => 'Riêng lẻ',
            '圆角值' => 'Giá trị bo góc',
            '建议：' => 'Gợi ý: ',
            '建议:' => 'Gợi ý: ',
            '输入连接' => 'Nhập liên kết',
            '输入标题' => 'Nhập tiêu đề',
            '默认logo' => 'Logo mặc định',
            '顶部固定logo' => 'Logo cố định phía trên',
            '提示文字' => 'Chữ gợi ý',
            '内容间距' => 'Khoảng cách nội dung',
            '下拉Danh mục' => 'Danh mục xổ xuống',
            '添加' => 'Thêm',
            '底部背景' => 'Nền phía dưới',
            '页面上间距' => 'Khoảng cách trên trang',
            '左右边距' => 'Khoảng cách trái phải',
            '上边距' => 'Khoảng cách trên',
            '下边距' => 'Khoảng cách dưới',
            '展示样式' => 'Kiểu hiển thị',
            '固定显示' => 'Hiển thị cố định',
            '分页滑动' => 'Vuốt theo trang',
            '显示行数' => 'Số hàng hiển thị',
            '导航样式' => 'Kiểu điều hướng',
            '图片+文字' => 'Ảnh + chữ',
            '单行显示' => 'Hiển thị 1 hàng',
            '个' => ' mục',
            '行' => ' hàng',
            '按钮颜色' => 'Màu nút',
            '按钮文字' => 'Chữ nút',
            '标题文字' => 'Chữ tiêu đề',
            '标题颜色' => 'Màu tiêu đề',
            '标题字号' => 'Cỡ chữ tiêu đề',
            '商品名称' => 'Tên sản phẩm',
            '商品价格' => 'Giá sản phẩm',
            '划线价' => 'Giá gạch ngang',
            '已售数量' => 'Đã bán',
            '按钮背景' => 'Nền nút',
            '优惠金额' => 'Giá trị giảm',
            '优惠券背景' => 'Nền mã giảm giá',
            '优惠券间距' => 'Khoảng cách mã giảm giá',
            '是否显示' => 'Có hiển thị',
            '列表设置' => 'Thiết lập danh sách',
            '商品设置' => 'Thiết lập sản phẩm',
            '通用样式' => 'Kiểu dùng chung',
            '头部设置' => 'Thiết lập đầu trang',
            '标题类型' => 'Kiểu tiêu đề',
            '背景色' => 'Màu nền',
            '背景图片' => 'Ảnh nền',
            '参与人数' => 'Số người tham gia',
            '砍价价格' => 'Giá mặc cả',
            '拼团价格' => 'Giá ghép nhóm',
            '秒杀价格' => 'Giá flash sale',
            '秒杀进度' => 'Tiến độ flash sale',
            '距离结束' => 'Thời gian còn lại',
            '数字背景' => 'Nền số',
            '数字' => 'Số',
            '新闻标题' => 'Tiêu đề tin',
            '时间日期' => 'Ngày giờ',
            '浏览量' => 'Lượt xem',
            '页面间距' => 'Khoảng cách trang',
            '请输入搜索词' => 'Nhập từ khóa tìm kiếm',
            '请输入标题文字' => 'Vui lòng nhập tiêu đề',
            '请输入右侧按钮' => 'Vui lòng nhập nút bên phải',
            '请输入右侧文字' => 'Vui lòng nhập chữ bên phải',
            '请输入标题' => 'Vui lòng nhập tiêu đề',
            '请输入链接' => 'Vui lòng nhập liên kết',
            '请输入Danh mục名称' => 'Vui lòng nhập tên danh mục',
            '请输入' => 'Vui lòng nhập',
            '选填' => 'Tùy chọn',
            '不超过4个字' => 'Không quá 4 ký tự',
            '不超过四' => 'Không quá 4',
            '不超过' => 'Không quá',
            '跟随主题风格' => 'Theo giao diện chủ đề',
            '自定义' => 'Tùy chỉnh',
            '颜色' => 'Màu sắc',
            '轮播搜索组件' => 'Thành phần banner tìm kiếm',
        ];
    }

    public static function translateString(string $value): string
    {
        $trimmed = trim($value);
        if ($trimmed === '') {
            return $value;
        }

        $exactMap = self::exactMap();
        if (isset($exactMap[$trimmed])) {
            return $exactMap[$trimmed];
        }

        return str_replace(array_keys(self::partialMap()), array_values(self::partialMap()), $value);
    }
}
